export { Hero } from "./Hero";
export { QuemFaz } from "./QuemFaz";
export { Services } from "./Services";
export { ComoFunciona } from "./ComoFunciona";
export { Cases } from "./Cases";
export { Testimonials } from "./Testimonials";
export { StackSection } from "./StackSection";
export { Faq } from "./Faq";
export { AiCta } from "./AiCta";
